ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    #certmanager.k8s.io/cluster-issuer: "letsencrypt-production"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    certmanager.k8s.io/acme-challenge-type: http01
  hosts:
    - name: chartmuseum.deart2k.com
      path: /
      tls: true
      tlsSecret: letsencrypt-production
env:
  open:
    # Enable API requests to upload charts to chartmuseum
    DISABLE_API: false