---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hipster-shop
spec:
  rules:
    - host: shop.deart2k.com
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend
              servicePort: 80
